{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9050fff9-2e51-40c8-a6fc-620b488c14a7",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import re\n",
    "import string\n",
    "\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.feature_extraction.text import TfidfVectorizer\n",
    "from sklearn.linear_model import LogisticRegression\n",
    "from sklearn.metrics import accuracy_score\n",
    "\n",
    "\n",
    "\n",
    "st.set_page_config(\n",
    "    page_title=\"Fake News Detection\",\n",
    "    page_icon=\"📰\",\n",
    "    layout=\"centered\"\n",
    ")\n",
    "\n",
    "st.title(\"📰 Fake News Detection\")\n",
    "st.write(\"Detect whether a news article is **Real** or **Fake** using Machine Learning.\")\n",
    "\n",
    "\n",
    "\n",
    "@st.cache_data\n",
    "def load_data():\n",
    "    fake = pd.read_csv(\"Fake.csv\")\n",
    "    true = pd.read_csv(\"True.csv\")\n",
    "\n",
    "    fake[\"label\"] = 0\n",
    "    true[\"label\"] = 1\n",
    "\n",
    "    data = pd.concat([fake, true], ignore_index=True)\n",
    "    data = data.sample(frac=1, random_state=42)\n",
    "\n",
    "    data[\"content\"] = data[\"title\"] + \" \" + data[\"text\"]\n",
    "\n",
    "    return data\n",
    "\n",
    "\n",
    "\n",
    "def clean_text(text):\n",
    "    text = text.lower()\n",
    "    text = re.sub(r\"http\\\\S+\", \"\", text)\n",
    "    text = re.sub(r\"<.*?>\", \"\", text)\n",
    "    text = re.sub(r\"\\\\d+\", \"\", text)\n",
    "    text = text.translate(str.maketrans(\"\", \"\", string.punctuation))\n",
    "    text = re.sub(r\"\\\\s+\", \" \", text).strip()\n",
    "\n",
    "    return text\n",
    "\n",
    "\n",
    "\n",
    "@st.cache_resource\n",
    "def train_model():\n",
    "\n",
    "    data = load_data()\n",
    "\n",
    "    data[\"content\"] = data[\"content\"].apply(clean_text)\n",
    "\n",
    "    X = data[\"content\"]\n",
    "    y = data[\"label\"]\n",
    "\n",
    "    X_train, X_test, y_train, y_test = train_test_split(\n",
    "        X,\n",
    "        y,\n",
    "        test_size=0.2,\n",
    "        random_state=42\n",
    "    )\n",
    "\n",
    "    vectorizer = TfidfVectorizer(\n",
    "        stop_words=\"english\",\n",
    "        max_df=0.7\n",
    "    )\n",
    "\n",
    "    X_train = vectorizer.fit_transform(X_train)\n",
    "    X_test = vectorizer.transform(X_test)\n",
    "\n",
    "    model = LogisticRegression(max_iter=1000)\n",
    "\n",
    "    model.fit(X_train, y_train)\n",
    "\n",
    "    accuracy = accuracy_score(\n",
    "        y_test,\n",
    "        model.predict(X_test)\n",
    "    )\n",
    "\n",
    "    return model, vectorizer, accuracy\n",
    "\n",
    "\n",
    "model, vectorizer, accuracy = train_model()\n",
    "\n",
    "st.success(f\"Model Accuracy: {accuracy:.2%}\")\n",
    "\n",
    "\n",
    "\n",
    "st.subheader(\"Enter News Article\")\n",
    "\n",
    "news = st.text_area(\n",
    "    \"Paste the news text here:\",\n",
    "    height=250\n",
    ")\n",
    "\n",
    "\n",
    "\n",
    "if st.button(\"Predict\"):\n",
    "\n",
    "    if news.strip() == \"\":\n",
    "        st.warning(\"Please enter a news article.\")\n",
    "    else:\n",
    "\n",
    "        cleaned = clean_text(news)\n",
    "\n",
    "        vector = vectorizer.transform([cleaned])\n",
    "\n",
    "        prediction = model.predict(vector)[0]\n",
    "\n",
    "        probability = model.predict_proba(vector)[0]\n",
    "\n",
    "        if prediction == 1:\n",
    "            st.success(\"✅ This appears to be REAL news.\")\n",
    "            st.write(f\"Confidence: **{probability[1]*100:.2f}%**\")\n",
    "        else:\n",
    "            st.error(\"❌ This appears to be FAKE news.\")\n",
    "            st.write(f\"Confidence: **{probability[0]*100:.2f}%**\")\n",
    "\n",
    "\n",
    "\n",
    "if st.checkbox(\"Show Dataset\"):\n",
    "\n",
    "    st.subheader(\"Dataset Preview\")\n",
    "\n",
    "    data = load_data()\n",
    "\n",
    "    st.dataframe(data.head())\n",
    "\n",
    "\n",
    "\n",
    "st.markdown(\"---\")\n",
    "st.write(\"Developed using Streamlit, Scikit-learn, and the Fake & Real News Dataset.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "389765af-a908-4b35-b9a9-4f035fff7da4",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
